# Generated by Django 4.2.3 on 2023-07-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("episode_id", models.IntegerField()),
                ("opening_crawl", models.TextField()),
                ("director", models.CharField(max_length=255)),
                ("producer", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("characters", models.TextField()),
                ("planets", models.TextField()),
                ("starships", models.TextField()),
                ("vehicles", models.TextField()),
                ("species", models.TextField()),
                ("created", models.DateTimeField()),
                ("edited", models.DateTimeField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rotation_period", models.CharField(max_length=255)),
                ("orbital_period", models.CharField(max_length=255)),
                ("diameter", models.CharField(max_length=255)),
                ("climate", models.CharField(max_length=255)),
                ("gravity", models.CharField(max_length=255)),
                ("terrain", models.CharField(max_length=255)),
                ("surface_water", models.CharField(max_length=255)),
                ("population", models.CharField(max_length=255)),
                ("residents", models.TextField()),
                ("films", models.TextField()),
                ("created", models.DateTimeField()),
                ("edited", models.DateTimeField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("custom_title", models.CharField(max_length=255)),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="favourites.movie",
                    ),
                ),
                (
                    "planet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="favourites.planet",
                    ),
                ),
            ],
        ),
    ]
