# Generated by Django 4.2.3 on 2023-07-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favourites", "0002_moviefavourite_planetfavourite_delete_favourite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviefavourite",
            name="custom_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="planetfavourite",
            name="custom_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
